# July 9, 2024
# Configuration file for AFN fines and fees report script

port:  25
username:  ""
password:  ""

# The directory from which the report should begin searching for files prefixed with al-
scriptpath: "."

# The simple mail transfer protocol server that will send notifications to AFN leads to pick up their reports
smtpserver: "sandbox.smtp.mailtrap.io"

# The sending address
email_source:  ""

# Subject line in email
email_subject: "Your AFN fines and fees report is ready for pick-up"

#Email recipients; a list of strings that should contain AFN instition leads
email_recipients: ["", ""]

message:  "Please check your folder on the Scholars Portal server to pick up your fines and fees report"
